#!/usr/bin/python
########################################################
############## trata_fich_creado #######################
########################################################

# ### whatFileisIt ###
from mylib import *
import os,sys,re,argparse,shutil,glob,shlex

# WhatFileisIt (path/to/file)
#def executa (command):
        # Ejecutar comando
        #process=subprocess.Popen(command,shell=True,stdout=subprocess.PIPE)
#        print "COMANDO A EJECUTAR:"+command
	
#	theargs=shlex.split(command)
#	print theargs
#        process=subprocess.Popen(theargs,stdout=subprocess.PIPE)
        # Eliminar espacios en blanco sobrantes
#       output= process.stdout.readline().strip()
#        output = process.communicate()[0].strip()
#        output = process.communicate()[0]
        # Dividir en lineas
#        output = output.split('\n')
#        print output
#        return output


#def whatFileisIt(text):
def whatFileisIt(InputFile):

	# RUn file command
        result=executa("file --mime-type '"+str(InputFile)+"'")
	# Get file name
	text=result[0].split(":")[1]
	#print result
#	mime= magic.Magic(mime=True)
#	mime.from_file(ficherin)
        #print text
        if 'image' in text:
#(re.search('image',text)):
                print "Es una imagen"
                return 1
                # Treat the image
        #if (re.search('zip|tar|rar',text)):
#        if (re.search('compressed',text)):
	if 'zip' or 'rar' or 'tar.gz' in text:
               print "Es un fichero comprimido"
               return 2

###### DoItWithCompressed
def DoItWithCompressed(FileToUncompress,BaseDir,BaseDirOutput):
	tempdir,zipdir,FileZipName=uncompress(FileToUncompress,BaseDir)
	compress(tempdir,zipdir,BaseDirOutput+"/"+FileZipName)
###### Compress
def compress(tempdir,DirToZip,FileNameZip):
	#for (fullpath, _, AllFiles) in os.walk(tempdir):
	for CurrentFile in glob.glob(tempdir+"/*"):
		if os.path.isfile(CurrentFile):
        		os.chmod(CurrentFile,0755)
			FixedCurrentFile=remove_weirdchars(CurrentFile)
        		watermarkea(FixedCurrentFile,DirToZip)
        ## Compress watermarked files
        ### Output file: basedir/zipdir.zip
	#DirWMName=
        #CompressedOutputFile=DirWMName[:-1]+".zip" if DirWMName[-1]=='/' else DirWMName+".zip"
        ### Exec command
        command='7z a -tzip '+FileNameZip+".zip"+' '+DirToZip
        print command
        result=executa(command)
        ## Delete temp dir
        print "Removedirs de "+tempdir
	shutil.rmtree(tempdir, ignore_errors=True)

####### Gen_PathFileZipName
def Gen_PathFileZipName(FileToUncompress):
	# Get file name.Search last point
	#if FileToUncompress.find("."):
		#FileZip=FileToUncompress.partition(".")[FileToUncompress.rfind(".")]
	FileZip=FileToUncompress[:FileToUncompress.rfind(".")] if FileToUncompress.find(".") else FileToUncompress
#	else:
#		FileZip=FileToUncompress
#	print "*** FileZip ***"+str(FileZip)
#	exit(1)
        ##### HERE ####
	## Check if filenames are web compatible
#	FileWMName=remove_weirdchars(FileZip)
	FileWMName=os.path.basename(FileZip)
        DirWMName=FileWMName+"_WM"

	return DirWMName


def create_tempdir(FileZipName):
	# Create temp dir
        tempdir=BaseDir+"/"+executa('</dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-8};echo;')[0]
        # Create temp dir
        #print "DIR TEMPORAL:"+tempdir
        #os.mkdir(tempdir,0777)
        ## Create temp dir with filename
        #FileZip=FileToUncompress.partition(".")[0]
        #FileWMName=os.path.basename(FileZip)
        #DirWMName=FileWMName+"_WM"

        zipdir=tempdir+"/"+FileZipName+"/"
        os.makedirs(zipdir)
        os.chmod(tempdir,0777)
        os.chmod(zipdir,0777)

#	return tempdir,zipdir,BaseDir+"/"+DirWMName
	return tempdir,zipdir
##### Gen_ZipDir
def Gen_ZipDir(FileToUncompress):
	FileZipName=Gen_PathFileZipName(FileToUncompress)
        tempdir,zipdir=create_tempdir(FileZipName)

	return FileZipName,tempdir,zipdir

##### Uncompress
def uncompress(FileToUncompress,BaseDir):
	# Create temp dir
#	tempdir=BaseDir+"/"+executa('< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-8};echo;')[0]
	# Create temp dir
	#print "DIR TEMPORAL:"+tempdir
	#os.mkdir(tempdir,0777)
	## Create temp dir with filename
#	FileZip=FileToUncompress.partition(".")[0]
#	FileWMName=os.path.basename(FileZip)
#	DirWMName=FileWMName+"_WM"
	
#	zipdir=tempdir+"/"+DirWMName+"/"
#	os.makedirs(zipdir)
#	os.chmod(tempdir,0777)
#	os.chmod(zipdir,0777)
#	FileZipName=gen_FileZipName(FileToUncompress)
#	tempdir,zipdir=create_tempdir(FileZipName)
	FileZipName,tempdir,zipdir=Gen_ZipDir(FileToUncompress)
	# Uncompress
	command='7z e -o'+tempdir+' '+FileToUncompress
	# print command
	ficheros=executa(command)
	# Change permissions
	#for CadaFich in ficheros:
	#	os.chmod(CadaFich,0755)
	# Watermark
	## For each file in dir, do watermark
#	compress(tempdir,zipdir,BaseDir+"/"+os.path.basename(DirWMName))
	#FileZip=BaseDir+"/"+FileZipName
	if Debug:
		print "TEMPD:"+tempdir
		print "ZIPDIR:"+zipdir
		print "FILEZIPNAME:"+FileZipName
	#compress(tempdir,zipdir,FileZipName)
	return tempdir,zipdir,FileZipName
	#os.removedirs(zipdir)
	

def Gen_OutputFile(ArgsInputFile,ArgsOutput):
#	print "[[[ VAMOS A VER TRATANDO "+ArgsInputFile+" ]]]"
#	print "ArgsOutput es un..."+"directorio"if os.path.isdir(ArgsOutput) else "fichero"
	
	BaseDir=ArgsOutput if os.path.isdir(ArgsOutput) else os.path.dirname(ArgsOutput)
	#BaseDir=BaseDir+"/"+ArgsInputFile
        if os.path.isdir(ArgsOutput):
                OutputFile=BaseDir+ArgsInputFile
	return OutputFile

def remove_weirdchars(FromFile):
	#return FromFile.replace(" ","_")
	#return re.sub("[\(\) ]+","_",FromFile)
	OnlyFileName=os.path.basename(FromFile)
	print "!!!!! OnlyFileName "+OnlyFileName
	FixedName=re.sub("[^\w0-9-\._]+","_",OnlyFileName)
	PathAndFixedName=os.path.dirname(FromFile)+"/"+FixedName
	print "!!!!! FROM "+FromFile+" TO "+PathAndFixedName
	if FixedName != OnlyFileName:
		os.rename(FromFile,PathAndFixedName)
	else:
		print "SON IGUALES.NO RENOMBRO"
        return PathAndFixedName
	#InputFile=FileWithoutWeirdChars
# watermarkea(Input file, output file)	
def watermarkea(InputFile,OutputFile):
	result=executa('su - fotos -c \'/usr/local/bin/pon_marcaagua.py \"'+InputFile+'\" \"'+ OutputFile+'\"\'')

	###############################
	########## MAIN ###############
	###############################

parser= argparse.ArgumentParser()
parser.add_argument("-i","--input-file",dest='TheFile',required=True,help="Input file")
# Default Output dir: same than inputfile
parser.add_argument("-o","--output",dest='Output',help="Output dir/file")
parser.add_argument("-w","--wtf",dest='WatermarkFile',help="Watermark file")
parser.add_argument("--debug",dest='Debug',help="Debug output")
args=parser.parse_args()


BaseDirOutput=os.path.dirname(args.TheFile) if not args.Output else args.Output
BaseDir=os.path.dirname(args.TheFile)
OnlyFileName=os.path.basename(args.TheFile)
Debug=args.Debug
#parser.parse_args(['-i','/mnt/compartir/afotos/convierte/FOTOS_AQUI/avion.jpg'])
#TheFile=sys.argv[1]
if os.path.isfile(args.TheFile):
#	FileWithoutWeirdChars=BaseDir+"/"+remove_weirdchars(OnlyFileName)
	InputFile=remove_weirdchars(args.TheFile)
	print "!!!!!!!!!!!!!!FICH RENOMBRADO:"+InputFile
	# Rename file to remove whitespaces
	#FileWithoutWeirdChars=
	#os.rename(args.TheFile,FileWithoutWeirdChars)
#	InputFile=FileWithoutWeirdChars
	
	#print "FICHERO RENOMBRADO:"+FileWithoutWspaces
#        result=executa("file -i "+str(InputFile))
#	whatItIs=whatFileisIt((result[0].split(":"))[1])
	whatItIs=whatFileisIt(InputFile)

#	whatItIs=whatFileisIt(str(InputFile))
	### TEST #### 
        #whatItIs=2 # <--
	# Single file
	if whatItIs == 2:
		# Compressed file
		# Create temp dir
		## Generate random dir
		## Uncompress
		DoItWithCompressed(InputFile,BaseDir,BaseDirOutput)
		#uncompress(InputFile,BaseDir,BaseDir)
		#compress(tempdir,zipdir,FileZipName)
	else:
		OutputFile=BaseDirOutput+os.path.basename(InputFile)
		watermarkea(InputFile,OutputFile)
		#result=executa('su - fotos -c "/usr/local/bin/pon_marcaagua.py \"'+args.TheFile+'\" '+ OutputFile)
#if [ $? -eq 0 ]; then
#	rm $1
#fi 
